# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GVLJluA_novNi09R7rUzn9YoXKLQweGT
"""

model_name1="Sarcasm+Humour.h5"
MAX_NB_WORDS=40000
MAX_SEQUENCE_LENGTH=128
EMBEDDING_DIM=300
VALIDATION_SPLIT=0.2
max_sentences=10
max_words=128
word_encoding_dim=300
sentence_encoding_dim=128
n_epochs =15
batch_size =32

